# Generated by Django 3.0.5 on 2020-10-17 08:26

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comment', djongo.models.fields.JSONField()),
                ('date', models.DateField()),
            ],
        ),
    ]
