# Generated by Django 3.0.5 on 2020-10-17 08:49

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('comment', djongo.models.fields.JSONField()),
                ('date', models.DateField()),
                ('tag', djongo.models.fields.JSONField()),
                ('author_details', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
