# Generated by Django 3.0.5 on 2020-10-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201017_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='id',
            new_name='_id',
        ),
    ]
