# Generated by Django 2.2.2 on 2020-11-09 12:01

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201017_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', djongo.models.fields.JSONField()),
                ('comment', djongo.models.fields.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
